[package]
name = "chessvault"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
application-runtime = { path = "../../crates/application-runtime" }
chess-core = { path = "../../crates/chess-core" }
iced = { version = "0.14.0", features = ["svg", "tokio"] }
serde.workspace = true
serde_json.workspace = true
tracing = "0.1.44"
tracing-log = "0.2"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
zerocopy.workspace = true

[dev-dependencies]
log = "0.4.34"
rstest.workspace = true
